name: Android Build

on:
  push:
    branches:
      - main  # Trigger on push to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the 'main' branch
  workflow_dispatch:  # Allows for manual triggering from the GitHub UI

jobs:
  build:
    name: Build Android Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: 6.0  # Specify the version of cmdline-tools (replace with the desired version)
          accept-android-sdk-licenses: true  # Accept licenses automatically

      - name: Grant execute permission to Gradle
        run: chmod +x gradlew

      - name: Build Project
        run: ./gradlew clean check

      - name: Cache Gradle files
        uses: actions/cache@v3
        with:
          path: ~/.gradle
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-
