name: Android Build

on:
  push:
    branches:
      - main  # Trigger on push to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the 'main' branch
  workflow_dispatch:  # Allows for manual triggering from the GitHub UI

jobs:
  build:
    name: Build Android Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install Android SDK Tools
        run: |
          # Set ANDROID_HOME variable
          export ANDROID_HOME=$HOME/Android/Sdk
          mkdir -p $ANDROID_HOME

          # Download the full SDK Tools package
          wget https://dl.google.com/android/repository/commandlinetools-linux-12266719_latest.zip -O /tmp/commandlinetools.zip
          unzip /tmp/commandlinetools.zip -d $ANDROID_HOME
          rm /tmp/commandlinetools.zip

          # Install SDK components
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH

          # Verify sdkmanager existence
          sdkmanager --version

          # Accept licenses and install necessary components
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "tools" "build-tools;30.0.3" "android-30"

      - name: Grant execute permission to Gradle
        run: chmod +x gradlew

      - name: Build Project
        run: ./gradlew clean check

      - name: Cache Gradle files
        uses: actions/cache@v3
        with:
          path: ~/.gradle
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-
